Repository kurkle/chartjs-chart-treemap, pull requests merged in 2021-11, with the labels that each got.

#51 Adds styling options to the labels
  docs/.vuepress/config.js
  docs/integration.md
  docs/samples/labels.md
  docs/usage.md
  src/controller.js
  src/element.js
  test/fixtures/basic/labelsAlign.js
  test/fixtures/basic/labelsAlign.png
  test/fixtures/basic/labelsFormatter.js
  test/fixtures/basic/labelsFormatter.png
  test/fixtures/basic/labelsPadding.js
  test/fixtures/basic/labelsPadding.png
  test/fixtures/basic/labelsPosition.js
  test/fixtures/basic/labelsPosition.png
  types/index.esm.d.ts
  types/tests/options.ts
Labels: enhancement

#54 Adds "captions" object to configure the styles of the captions (group labels)
  docs/.vuepress/config.js
  docs/samples/captions.md
  docs/usage.md
  src/controller.js
  src/element.js
  test/fixtures/basic/labelsAlign.png
  test/fixtures/basic/labelsColor.js
  test/fixtures/basic/labelsColor.png
  test/fixtures/basic/labelsFont.js
  test/fixtures/basic/labelsFont.png
  test/fixtures/basic/labelsMultilineFormatter.js
  test/fixtures/basic/labelsMultilineFormatter.png
  test/fixtures/basic/labelsPosition.png
  test/fixtures/grouped/captionsAlign.js
  test/fixtures/grouped/captionsAlign.png
  test/fixtures/grouped/captionsColor.js
  test/fixtures/grouped/captionsColor.png
  test/fixtures/grouped/captionsFont.js
  test/fixtures/grouped/captionsFont.png
  test/fixtures/grouped/captionsFormatter.js
  test/fixtures/grouped/captionsFormatter.png
  test/fixtures/grouped/captionsPadding.js
  test/fixtures/grouped/captionsPadding.png
  test/fixtures/grouped/labelsFormatter.js
  test/fixtures/grouped/labelsFormatter.png
  types/index.esm.d.ts
  types/tests/options.ts
Labels: enhancement

#55 Adds "dividers" object to configure the dividers (group dividers)
  docs/.vuepress/config.js
  docs/samples/dividers.md
  docs/usage.md
  samples/dividers.html
  src/controller.js
  src/element.js
  test/fixtures/grouped/dividers.js
  test/fixtures/grouped/dividers.png
  types/index.esm.d.ts
  types/tests/options.ts
Labels: enhancement

#60 Fix captions drawing
  src/controller.js
  test/fixtures/grouped/captionsFormatter.png
  test/fixtures/grouped/captionsPadding.png
Labels: enhancement

#59 Clean unused options
  src/element.js
  test/fixtures/grouped/basic.js
  test/fixtures/grouped/border.js
Labels: chore

#64 Bump version to 2.0.0, update deps, update actions
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/npmpublish.yml
  package-lock.json
  package.json
Labels: major, chore
