Repository kurkle/chartjs-chart-treemap, pull requests merged in 2022-10, with the labels that each got.

#130 Fix defaults value of the options on the documentation
  docs/usage.md
  src/element.js
Labels: documentation, chore

#131 Fix the rectangles size calculation aligning to bar element logic
  docs/usage.md
  src/controller.js
  src/element.js
  test/fixtures/basic/borderRadiusIsIgnored.js
  test/fixtures/basic/borderRadiusIsIgnored.png
  test/fixtures/basic/borderWidth.png
  test/fixtures/grouped/borderWidthAsObject.js
  test/fixtures/grouped/borderWidthAsObject.png
Labels: enhancement, refactoring

#141 Enable zoom plugin on treemap controller
  docs/.vuepress/config.js
  docs/samples/zoom.md
  docs/scripts/register.js
  package-lock.json
  package.json
  src/controller.js
  src/utils.js
  test/fixtures/basic/differentAxes.js
  test/fixtures/basic/differentAxes.png
  test/fixtures/basic/noXAxes.js
  test/fixtures/basic/noXAxes.png
  test/fixtures/basic/noYAxes.js
  test/fixtures/basic/noYAxes.png
  test/fixtures/grouped/treeUngrouped.js
  test/fixtures/grouped/treeUngrouped.png
Labels: enhancement

#147 Fix captions check when display option is not defined
  src/controller.js
  src/element.js
  test/fixtures/basic/labelsMultilineColors.js
  test/fixtures/basic/labelsMultilineFonts.js
  test/fixtures/grouped/captionsWithoutDisplay.js
  test/fixtures/grouped/captionsWithoutDisplay.png
Labels: bug

#148 Add includeInvisible option to interaction to manage negative spacing options
  README.md
  package-lock.json
  package.json
  src/controller.js
  test/fixtures/events/hoverNegativeSpacing.js
  test/fixtures/events/hoverNegativeSpacing.png
Labels: bug

#150 Fix hovering on labels and captions
  src/element.js
  test/fixtures/events/hoverCaptions.js
  test/fixtures/events/hoverCaptions.png
  test/fixtures/events/hoverLabels.js
  test/fixtures/events/hoverLabels.png
Labels: bug

#152 Bump 2.1.2, remove unneeded imports from fixtures
  package-lock.json
  package.json
  test/.eslintrc.yml
  test/fixtures/events/hover.js
  test/fixtures/events/hoverCaptions.js
  test/fixtures/events/hoverLabels.js
  test/fixtures/events/hoverNegativeSpacing.js
  test/fixtures/events/tooltip.js
Labels: chore
