Repository kurkle/chartjs-chart-treemap, pull requests merged in 2022-09, with the labels that each got.

#97 Add VisualElement extension to Treemap element type definition
  types/index.esm.d.ts
Labels: types

#99 Use isObject from CHART.JS helpers instead of an internal one
  src/element.js
  src/utils.js
  test/specs/utils.spec.js
Labels: chore

#104 Update deps
  karma.conf.js
  package-lock.json
  package.json
Labels: dependencies

#102 Move all drawings (captions, labels and dividers) in the element drawing
  src/controller.js
  src/element.js
Labels: enhancement

#98 Enable tree data as an object using the hierarchy of its properties
  docs/.vuepress/config.js
  docs/samples/tree.md
  docs/scripts/data.js
  docs/usage.md
  src/controller.js
  src/element.js
  src/utils.js
  test/fixtures/grouped/treeBasic.js
  test/fixtures/grouped/treeBasic.png
  test/fixtures/grouped/treeBasicAndCaptions.js
  test/fixtures/grouped/treeBasicAndCaptions.png
  test/fixtures/grouped/treeBasicWithGroupsNumbers.js
  test/fixtures/grouped/treeBasicWithGroupsNumbers.png
  test/fixtures/grouped/treeBasicWithLeafKey.js
  test/fixtures/grouped/treeBasicWithLeafKey.png
  test/specs/utils.spec.js
  types/index.esm.d.ts
Labels: enhancement

#107 Add sample using Datalabels plugin
  docs/.vuepress/config.js
  docs/samples/datalabels.md
  docs/scripts/register.js
  package-lock.json
  package.json
Labels: documentation

#111 Emit warning when tooltip positioner is not registered
  src/controller.js
Labels: chore

#112 Remove documentation about Datalabels plugin incompatibility
  docs/usage.md
Labels: documentation

#115 Use borderWidth option correctly for the captions size calculation
  src/controller.js
  src/element.js
  test/fixtures/grouped/borderWidthAsObject.js
  test/fixtures/grouped/borderWidthAsObject.png
Labels: enhancement

#116 Add new categories to release drafter to improve PR groups
  .github/release-drafter.yml
Labels: infrastructure

#118 Replace var to const or let where used
  docs/integration.md
  docs/scripts/utils.js
  test/fixtures/events/hover.js
  test/fixtures/events/tooltip.js
  test/specs/utils.spec.js
Labels: infrastructure

#119 Add rtl property in the subrectangle to squarify groups
  src/controller.js
  test/fixtures/grouped/basic-rtl.js
  test/fixtures/grouped/basic-rtl.png
Labels: enhancement

#106 Add overflow option to labels configuration
  docs/samples/captions.md
  docs/usage.md
  src/element.js
  test/fixtures/basic/labelsMultilineOverflowCut.js
  test/fixtures/basic/labelsMultilineOverflowCut.png
  test/fixtures/basic/labelsMultilineOverflowHidden.js
  test/fixtures/basic/labelsMultilineOverflowHidden.png
  test/fixtures/basic/labelsOverflowCut.js
  test/fixtures/basic/labelsOverflowCut.png
  test/fixtures/basic/labelsOverflowHidden.js
  test/fixtures/basic/labelsOverflowHidden.png
  types/index.esm.d.ts
Labels: enhancement

#114 Enable borderRadius to the rectangles of treemap elements
  docs/samples/dividers.md
  docs/usage.md
  src/controller.js
  src/element.js
  test/fixtures/basic/borderRadius.js
  test/fixtures/basic/borderRadius.png
  test/fixtures/basic/borderRadiusAsObject.js
  test/fixtures/basic/borderRadiusAsObject.png
  test/fixtures/basic/borderRadiusIsIgnored.js
  test/fixtures/basic/borderRadiusIsIgnored.png
  test/fixtures/basic/borderWidth.js
  test/fixtures/basic/borderWidth.png
  test/fixtures/grouped/dividers.png
Labels: enhancement

#124 Fix multiline labels drawing position when centered
  package.json
  src/element.js
  test/fixtures/basic/labels.png
  test/fixtures/basic/labelsAlign.png
  test/fixtures/basic/labelsFormatter.png
  test/fixtures/basic/labelsMultilineFormatter.js
  test/fixtures/basic/labelsMultilineFormatter.png
  test/fixtures/basic/labelsMultilineOverflowCut.js
  test/fixtures/basic/labelsMultilineOverflowCut.png
  test/fixtures/basic/labelsMultilineOverflowHidden.png
  test/fixtures/basic/labelsOverflowCut.png
  test/fixtures/basic/labelsPadding.png
  test/fixtures/basic/labelsPosition.js
  test/fixtures/basic/labelsPosition.png
  test/fixtures/grouped/captionsAlign.png
  test/fixtures/grouped/captionsColor.js
  test/fixtures/grouped/captionsColor.png
  test/fixtures/grouped/captionsFont.png
  test/fixtures/grouped/captionsFormatter.png
  test/fixtures/grouped/captionsPadding.png
  test/fixtures/grouped/treeBasic.png
  test/fixtures/grouped/treeBasicAndCaptions.png
  test/fixtures/grouped/treeBasicWithGroupsNumbers.png
  test/fixtures/grouped/treeBasicWithLeafKey.png
Labels: bug

#132 Return strings from default formatter
  src/element.js
  test/fixtures/grouped/treeBasic.png
  test/fixtures/grouped/treeBasicAndCaptions.png
  test/fixtures/grouped/treeBasicWithGroupsNumbers.png
  test/fixtures/grouped/treeBasicWithLeafKey.png
Labels: bug

#128 Enable different fonts and colors configuration on multiline labels
  docs/.vuepress/config.js
  docs/samples/labelsFontsAndColors.md
  docs/usage.md
  package.json
  src/element.js
  test/fixtures/basic/labelsMultilineColors.js
  test/fixtures/basic/labelsMultilineColors.png
  test/fixtures/basic/labelsMultilineFonts.js
  test/fixtures/basic/labelsMultilineFonts.png
  types/index.esm.d.ts
  types/tests/options.ts
Labels: enhancement

#127 Enable spriteText on test cases where labels are drawn
  test/fixtures/basic/borderRadius.js
  test/fixtures/basic/borderRadius.png
  test/fixtures/basic/borderRadiusAsObject.js
  test/fixtures/basic/borderRadiusAsObject.png
  test/fixtures/basic/borderRadiusIsIgnored.js
  test/fixtures/basic/borderRadiusIsIgnored.png
  test/fixtures/basic/borderWidth.js
  test/fixtures/basic/borderWidth.png
  test/fixtures/basic/labels.js
  test/fixtures/basic/labels.png
  test/fixtures/basic/labelsAlign.js
  test/fixtures/basic/labelsAlign.png
  test/fixtures/basic/labelsColor.js
  test/fixtures/basic/labelsColor.png
  test/fixtures/basic/labelsFont.js
  test/fixtures/basic/labelsFont.png
  test/fixtures/basic/labelsFormatter.js
  test/fixtures/basic/labelsFormatter.png
  test/fixtures/basic/labelsMultilineFormatter.js
  test/fixtures/basic/labelsMultilineFormatter.png
  test/fixtures/basic/labelsMultilineOverflowCut.js
  test/fixtures/basic/labelsMultilineOverflowCut.png
  test/fixtures/basic/labelsMultilineOverflowHidden.js
  test/fixtures/basic/labelsMultilineOverflowHidden.png
  test/fixtures/basic/labelsOverflowCut.js
  test/fixtures/basic/labelsOverflowCut.png
  test/fixtures/basic/labelsOverflowHidden.js
  test/fixtures/basic/labelsOverflowHidden.png
  test/fixtures/basic/labelsPadding.js
  test/fixtures/basic/labelsPadding.png
  test/fixtures/basic/labelsPosition.js
  test/fixtures/basic/labelsPosition.png
  test/fixtures/grouped/captionsAlign.js
  test/fixtures/grouped/captionsAlign.png
  test/fixtures/grouped/captionsColor.js
  test/fixtures/grouped/captionsColor.png
  test/fixtures/grouped/captionsFont.js
  test/fixtures/grouped/captionsFont.png
  test/fixtures/grouped/captionsFormatter.js
  test/fixtures/grouped/captionsFormatter.png
  test/fixtures/grouped/captionsPadding.js
  test/fixtures/grouped/captionsPadding.png
  test/fixtures/grouped/labelsFormatter.js
  test/fixtures/grouped/labelsFormatter.png
  test/fixtures/grouped/treeBasic.js
  test/fixtures/grouped/treeBasicAndCaptions.js
  test/fixtures/grouped/treeBasicWithGroupsNumbers.js
  test/fixtures/grouped/treeBasicWithLeafKey.js
Labels: chore

#133 Update deps
  package-lock.json
  package.json
Labels: dependencies
